workflows:
  android-build:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        BUILD_DIR: build/app/outputs/flutter-apk
    scripts:
      - name: Remove android directory
        script: |
          rm -rf android
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run cleanup script
        script: |
          chmod +x ./remove_unused.sh
          ./remove_unused.sh
      - name: Flutter clean & get again
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --target-platform android-arm64
    artifacts:
      - $BUILD_DIR/app-arm64-v8a-release.apk
