workflows:
  android-build:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    vars:
      BUILD_DIR: build/app/outputs/flutter-apk
    scripts:
      - name: Remove android directory
        script: |
          echo "🔧 Removing android directory..."
          rm -rf android

      - name: Get dependencies
        script: |
          echo "📦 Running flutter pub get..."
          flutter pub get

      - name: Run cleanup script
        script: |
          echo "🧹 Running remove_unused.sh script..."
          chmod +x ./remove_unused.sh
          ./remove_unused.sh

      - name: Flutter clean & get again
        script: |
          echo "🧼 Running flutter clean and getting packages again..."
          flutter clean
          flutter pub get

      - name: Build APK
        script: |
          echo "🏗️ Building APK for android-arm64..."
          flutter build apk --target-platform android-arm64

    artifacts:
      - $BUILD_DIR/app-arm64-v8a-release.apk
