# ios/Podfile

platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
